namespace FMOD
{
	public enum DSP_PAN
	{
		MODE = 0,
		STEREO_POSITION = 1,
		SURROUND_DIRECTION = 2,
		SURROUND_EXTENT = 3,
		SURROUND_ROTATION = 4,
		SURROUND_LFE_LEVEL = 5,
		SURROUND_FROM_STEREO_MODE = 6,
		SURROUND_STEREO_SEPARATION = 7,
		SURROUND_STEREO_AXIS = 8,
		ENABLED_SURROUND_SPEAKERS = 9,
		_3D_POSITION = 10,
		_3D_ROLLOFF = 11,
		_3D_MIN_DISTANCE = 12,
		_3D_MAX_DISTANCE = 13,
		_3D_EXTENT_MODE = 14,
		_3D_SOUND_SIZE = 15,
		_3D_MIN_EXTENT = 16,
		_3D_PAN_BLEND = 17,
		LFE_UPMIX_ENABLED = 18,
		OVERALL_GAIN = 19,
		SURROUND_SPEAKER_MODE = 20
	}
}
