namespace FMOD
{
	public enum ERRORCALLBACK_INSTANCETYPE
	{
		NONE = 0,
		SYSTEM = 1,
		CHANNEL = 2,
		CHANNELGROUP = 3,
		CHANNELCONTROL = 4,
		SOUND = 5,
		SOUNDGROUP = 6,
		DSP = 7,
		DSPCONNECTION = 8,
		GEOMETRY = 9,
		REVERB3D = 10,
		STUDIO_SYSTEM = 11,
		STUDIO_EVENTDESCRIPTION = 12,
		STUDIO_EVENTINSTANCE = 13,
		STUDIO_PARAMETERINSTANCE = 14,
		STUDIO_CUEINSTANCE = 15,
		STUDIO_BUS = 16,
		STUDIO_VCA = 17,
		STUDIO_BANK = 18,
		STUDIO_COMMANDREPLAY = 19
	}
}
