namespace Kampai.UI.View
{
    public class UIContext : global::Kampai.Util.BaseContext
    {
        public UIContext()
        {
        }

        public UIContext(global::UnityEngine.MonoBehaviour view, bool autoStartup)
            : base(view, autoStartup)
        {
        }

        protected override void MapBindings()
        {
            injectionBinder.Bind<global::strange.extensions.context.api.ICrossContextCapable>().ToValue(this).ToName(global::Kampai.UI.View.UIElement.CONTEXT)
                .CrossContext();
            if (global::strange.extensions.context.impl.Context.firstContext == this)
            {
                injectionBinder.Bind<global::Kampai.Main.AppStartCompleteSignal>().ToSingleton().CrossContext();
            }
            global::UnityEngine.GameObject gameObject = global::UnityEngine.GameObject.Find("UI Root/UI Camera");
            injectionBinder.Bind<global::UnityEngine.Camera>().ToValue(gameObject.GetComponent<global::UnityEngine.Camera>()).ToName(global::Kampai.UI.View.UIElement.CAMERA)
                .CrossContext();
            injectionBinder.Bind<RushDialogPurchaseHelper>().To<RushDialogPurchaseHelper>();
            injectionBinder.Bind<global::Kampai.UI.View.SpawnDooberModel>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.QuestUIModel>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingModalParams>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.Model.LevelUpModel>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.IGUIService>().To<global::Kampai.UI.View.GUIService>().ToSingleton()
                .CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.AddStoreButtonSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.OnTabClickedSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.BuildMenuDefinitionLoadedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CurrencyMenuDefinitionLoadedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.BuildMenuButtonClickedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.AddStoreTabSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.MoveTabMenuSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.MoveHUDSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CloseHUDSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.ShowMoveBuildingMenuSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.ShowHUDSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.ShowSettingsButtonSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.PeekHUDSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.HideDelayHUDSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.SetHUDButtonsVisibleSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.TogglePopupForHUDSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.XPFTUEHighlightSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UsageSharingSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UsageSharingAcceptedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.ShowStoreSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.BuildMenuOpenedSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.FTUEProgressSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.FTUEQuestPanelCloseSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.FTUEQuestGoToSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.FTUEQuestFinished>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.FTUERewardClosed>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.FTUETikiOpened>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.SetBadgeForStoreTabSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.HighlightStoreItemSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.HideStoreHighlightSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SetBuildingRushedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.RushRevealBuildingSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SetNewUnlockForStoreTabSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SetNewUnlockForBuildMenuSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SetInventoryCountForBuildMenuSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.RemoveUnlockForBuildMenuSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.RemoveWorldProgressSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.RefreshDynamicRecipeSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CloseAllOtherMenuSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.IMailboxIconService>().To<global::Kampai.UI.MailboxIconService>().ToSingleton()
                .CrossContext();
            injectionBinder.Bind<global::Kampai.UI.IBuildMenuService>().To<global::Kampai.UI.BuildMenuService>().ToSingleton()
                .CrossContext();
            injectionBinder.Bind<global::Kampai.UI.IFancyUIService>().To<global::Kampai.UI.FancyUIService>().ToSingleton()
                .CrossContext();
            injectionBinder.Bind<global::Kampai.UI.IPositionService>().To<global::Kampai.UI.PositionService>().ToSingleton()
                .CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.LoadBuddyBarSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CloseBuddyFarewellPanelSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.OnDragItemSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.OnDropItemSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.OnDragItemOverDropAreaSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.OnDropItemOverDropAreaSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.CreateResourceIconSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.RemoveResourceIconSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.RemoveResourceIconsByTrackedIdSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateResourceIconCountSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.ShowAllResourceIconsSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.HideAllResourceIconsSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.ResetDoubleTapSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CreateWayFinderSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.RemoveWayFinderSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.GetWayFinderSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.SetLimitTikiBarWayFindersSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.ShowAllWayFindersSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.HideAllWayFindersSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateWayFinderPrioritySignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.AddQuestToExistingWayFinderSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.RemoveQuestFromExistingWayFinderSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.CenterCraftingIconSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.BuildingIdentificationSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateSliderSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.OrderBoardTicketClickedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.OrderBoardStartFillingPrestigeBarSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.OrderBoardTicketDeletedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.OrderBoardPrestigeSlotFullSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.OrderBoardHighLightFillOrderSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingModalClosedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingQueueHintStartSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingRecipeHintStartSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingRecipeUpdateSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingUpdateReagentsSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingHintStopSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingQueuePositionUpdateSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.RushDialogConfirmationSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateFacebookStateSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.ShowPreviousQuestDialogSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.ShowPromptSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.ShowPreviousPromptButtonSiganl>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.PromptReceivedSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.PreviousPromptReceivedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.QuestBookButtonHighlightSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.ShowRateAppPanelSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateQuestPanelWithNewQuestSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateQuestLineProgressSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CloseQuestBookSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.HideItemPopupSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.FTUELevelUpOpenSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.FTUELevelUpCloseSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.FTUECloseBuddySignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.InitializeSaleSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CharacterClickedSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.RequestCharacterSelectionSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SetBuildMenuEnabledSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.Util.DebugConsoleController>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateIdleMinionCountSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateSlotPurchaseButtonSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.DisableMoveToInventorySignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.FireXPVFXSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.FireGrindVFXSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.FirePremiumVFXSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SocialPartyFillOrderSetupUISignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SocialPartyFillOrderButtonMediatorUpdateSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SocialPartyFillOrderProfileButtonMediatorUpdateSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CurrencyDialogClosedSignal>().ToSingleton().CrossContext()
                .Weak();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingRecipeDragStartSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CraftingRecipeDragStopSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.DoobersFlownSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.MarketplaceCloseBuyPanelSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.MarketplaceOpenBuyPanelSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.MarketplaceCloseSalePanelSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.MarketplaceCloseAllSalePanels>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.MarketplaceOpenSalePanelSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SetNewSellItemSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateSaleSlotsStateSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.OpenCreateNewSalePanelSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.CloseCreateNewSalePanelSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateSaleSlotSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.UpdateBuySlotSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.RefreshSlotsSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.RemoveStorageBuildingItemDescriptionSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.EnableStorageBuildingItemDescriptionSignal>().ToSingleton();
            injectionBinder.Bind<global::Kampai.UI.View.SelectStorageBuildingItemSignal>().ToSingleton();
            base.mediationBinder.Bind<global::Kampai.UI.View.OfflineView>().To<global::Kampai.UI.View.OfflineMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.BuildMenuView>().To<global::Kampai.UI.View.BuildMenuMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.HUDView>().To<global::Kampai.UI.View.HUDMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CurrencyMenuView>().To<global::Kampai.UI.View.CurrencyMenuMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.TownHallButtonView>().To<global::Kampai.UI.View.TownHallButtonMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.DebrisModalItemView>().To<global::Kampai.UI.View.DebrisModalItemMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.DebrisModalView>().To<global::Kampai.UI.View.DebrisModalMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.ResourceIconPanelView>().To<global::Kampai.UI.View.ResourceIconPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.ResourceIconView>().To<global::Kampai.UI.View.ResourceIconMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.WorldProgressPanelView>().To<global::Kampai.UI.View.WorldProgressPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.FloatingTextPanelView>().To<global::Kampai.UI.View.FloatingTextPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.WayFinderPanelView>().To<global::Kampai.UI.View.WayFinderPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.WayFinderView>().To<global::Kampai.UI.View.WayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestWayFinderView>().To<global::Kampai.UI.View.QuestWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.OrderBoardWayFinderView>().To<global::Kampai.UI.View.OrderBoardWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.TSMWayFinderView>().To<global::Kampai.UI.View.TSMWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.TikiBarChildWayFinderView>().To<global::Kampai.UI.View.TikiBarChildWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.TikiBarParentWayFinderView>().To<global::Kampai.UI.View.TikiBarParentWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CabanaChildWayFinderView>().To<global::Kampai.UI.View.CabanaChildWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CabanaParentWayFinderView>().To<global::Kampai.UI.View.CabanaParentWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StorageBuildingWayFinderView>().To<global::Kampai.UI.View.StorageBuildingWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.BobPointsAtStuffWayFinderView>().To<global::Kampai.UI.View.BobPointsAtStuffWayFinderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.FloatingTextView>().To<global::Kampai.UI.View.FloatingTextMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.ProgressBarView>().To<global::Kampai.UI.View.ProgressBarMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.ItemListView>().To<global::Kampai.UI.View.ItemListMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.TabMenuView>().To<global::Kampai.UI.View.TabMenuMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.ResourceModalView>().To<global::Kampai.UI.View.ResourceModalMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MinionSliderView>().To<global::Kampai.UI.View.MinionSliderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MignettePlayConfirmView>().To<global::Kampai.UI.View.MignettePlayConfirmMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MignetteCallMinionsView>().To<global::Kampai.UI.View.MignetteCallMinionsMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MignetteCooldownMenuView>().To<global::Kampai.UI.View.MignetteCooldownMenuMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MignetteHUDView>().To<global::Kampai.UI.View.MignetteHUDMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MignetteScoreSummaryView>().To<global::Kampai.UI.View.MignetteScoreSummaryMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SaleView>().To<global::Kampai.UI.View.SaleMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.PopupConfirmationView>().To<global::Kampai.UI.View.PopupConfirmationMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StickerbookModalView>().To<global::Kampai.UI.View.StickerbookModalMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StickerbookCharacterView>().To<global::Kampai.UI.View.StickerbookCharacterMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StickerbookStickerView>().To<global::Kampai.UI.View.StickerbookStickerMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StickerbookDescriptionView>().To<global::Kampai.UI.View.StickerbookDescriptionMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CraftingPopupView>().To<global::Kampai.UI.View.CraftingPopupMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.GenericPopupView>().To<global::Kampai.UI.View.GenericPopupMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.DragDropItemView>().To<global::Kampai.UI.View.DragDropItemMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.DropAreaView>().To<global::Kampai.UI.View.DropAreaMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CompositeBuildingMenuView>().To<global::Kampai.UI.View.CompositeBuildingMenuMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MoveBuildingMenuView>().To<global::Kampai.UI.View.MoveBuildingMenuMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.RandomDropView>().To<global::Kampai.UI.View.RandomDropMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CurrencyWarningDialogView>().To<global::Kampai.UI.View.CurrencyWarningDialogMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CraftingModalView>().To<global::Kampai.UI.View.CraftingModalMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CraftingQueueView>().To<global::Kampai.UI.View.CraftingQueueMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CraftingRecipeView>().To<global::Kampai.UI.View.CraftingRecipeMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.OrderBoardModalView>().To<global::Kampai.UI.View.OrderBoardModalMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.OrderBoardTicketView>().To<global::Kampai.UI.View.OrderBoardTicketMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.OrderBoardTicketDetailView>().To<global::Kampai.UI.View.OrderBoardTicketDetailMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.BuddyBarView>().To<global::Kampai.UI.View.BuddyBarMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestPanelView>().To<global::Kampai.UI.View.QuestPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestLineProgressBarView>().To<global::Kampai.UI.View.QuestLineProgressBarMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.ProceduralQuestView>().To<global::Kampai.UI.View.ProceduralQuestMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.NotificationsView>().To<global::Kampai.UI.View.NotificationsMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestView>().To<global::Kampai.UI.View.QuestMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestStepView>().To<global::Kampai.UI.View.QuestStepMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestRewardView>().To<global::Kampai.UI.View.QuestRewardMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestTimerView>().To<global::Kampai.UI.View.QuestTimerMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MailboxIconView>().To<global::Kampai.UI.View.MailboxIconMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.LevelUpRewardView>().To<global::Kampai.UI.View.LevelUpRewardMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.GenericRushDialogView>().To<global::Kampai.UI.View.GenericRushDialogMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.LandExpansionRushDialogView>().To<global::Kampai.UI.View.LandExpansionRushDialogMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StorageBuildingModalView>().To<global::Kampai.UI.View.StorageBuildingModalMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StorageBuildingSaleSlotView>().To<global::Kampai.Game.View.StorageBuildingSaleSlotMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StorageBuildingItemView>().To<global::Kampai.UI.View.StorageBuildingItemMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SellPanelView>().To<global::Kampai.UI.View.SellPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.BuyMarketplacePanelView>().To<global::Kampai.UI.View.BuyMarketplacePanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CreateNewSellView>().To<global::Kampai.UI.View.CreateNewSellMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SellQuantityButtonView>().To<global::Kampai.UI.View.SellQuantityButtonMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.BuyMarketplaceSlotView>().To<global::Kampai.UI.View.BuyMarketplaceSlotMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.StorageBuildingItemInfoView>().To<global::Kampai.UI.View.StorageBuildingItemInfoMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.DLCIndicatorView>().To<global::Kampai.UI.View.DLCIndicatorMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.DLCDialogView>().To<global::Kampai.UI.View.DLCDialogMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MessagePopupView>().To<global::Kampai.UI.View.MessagePopupMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.TipsPopupView>().To<global::Kampai.UI.View.TipsPopupMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.QuestDialogView>().To<global::Kampai.UI.View.QuestDialogMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SkrimView>().To<global::Kampai.UI.View.SkrimMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.HUDSettingsButtonView>().To<global::Kampai.UI.View.HUDSettingsButtonMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SettingsMenuView>().To<global::Kampai.UI.View.SettingsMenuMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SettingsPanelView>().To<global::Kampai.UI.View.SettingsPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.FAQPanelView>().To<global::Kampai.UI.View.FAQPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.CreditsPanelView>().To<global::Kampai.UI.View.CreditsPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.AboutPanelView>().To<global::Kampai.UI.View.AboutPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.UsageSharingView>().To<global::Kampai.UI.View.UsageSharingMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.HelpPanelView>().To<global::Kampai.UI.View.HelpPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.NotificationsPanelView>().To<global::Kampai.UI.View.NotificationsPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.MockStoreView>().To<global::Kampai.UI.View.MockStoreMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.RateAppPanelView>().To<global::Kampai.UI.View.RateAppPanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.BillingNotAvailablePanelView>().To<global::Kampai.UI.View.BillingNotAvailablePanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.BuddyWelcomePanelView>().To<global::Kampai.UI.View.BuddyWelcomePanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.COPPAAgeGatePanelView>().To<global::Kampai.UI.View.COPPAAgeGatePanelMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.TownHallDialogView>().To<global::Kampai.UI.View.TownHallDialogMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.NudgeUpgradeDialogView>().To<global::Kampai.UI.View.NudgeUpgradeDialogMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyStartView>().To<global::Kampai.UI.View.SocialPartyStartMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyFBConnectView>().To<global::Kampai.UI.View.SocialPartyFBConnectMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyInviteAlertView>().To<global::Kampai.UI.View.SocialPartyInviteAlertMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyRewardView>().To<global::Kampai.UI.View.SocialPartyRewardMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyFillOrderView>().To<global::Kampai.UI.View.SocialPartyFillOrderMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyFillOrderButtonView>().To<SocialPartyFillOrderButtonMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyFillOrderProfileButtonView>().To<SocialPartyFillOrderProfileButtonMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyEventEndView>().To<global::Kampai.UI.View.SocialPartyEventEndMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyEventCompletedView>().To<global::Kampai.UI.View.SocialPartyEventCompletedMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.SocialPartyNoEventView>().To<global::Kampai.UI.View.SocialPartyNoEventMediator>();
            base.mediationBinder.Bind<global::Kampai.UI.View.FacebookConnectPopupView>().To<global::Kampai.UI.View.FacebookConnectPopupMediator>();
            base.mediationBinder.Bind<global::Kampai.Game.View.ParticleSystemAudioHandlerView>().To<global::Kampai.Game.View.ParticleSystemAudioHandlerMediator>();
            base.mediationBinder.Bind<global::Kampai.Util.AnimatorStateInfo.AnimatorStateView>().To<global::Kampai.Util.AnimatorStateInfo.AnimatorStateMediator>();
            base.commandBinder.Bind<global::Kampai.Common.StartSignal>().To<global::Kampai.UI.View.UIStartCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.LoadGUISignal>().To<global::Kampai.UI.View.LoadGUICommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.LoadDefinitionForUISignal>().To<global::Kampai.UI.View.LoadDefinitionForUICommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.CurrencyButtonClickSignal>().To<global::Kampai.UI.View.CurrencyButtonClickCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowBuildingDetailMenuSignal>().To<global::Kampai.UI.View.ShowBuildingDetailMenuCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ToggleFPSGraphSignal>().To<global::Kampai.UI.View.ToggleFPSGraphCommand>();
            global::Kampai.Util.FastPooledCommandBinder<global::UnityEngine.Vector3, global::Kampai.UI.View.DestinationType, int, bool>.Bind<global::Kampai.UI.View.SpawnDooberSignal, global::Kampai.UI.View.SpawnDooberCommand>(injectionBinder);
            global::Kampai.Util.FastPooledCommandBinder<global::Kampai.UI.View.MignetteHUDView, global::UnityEngine.Vector3, int, bool>.Bind<global::Kampai.UI.View.SpawnMignetteDooberSignal, global::Kampai.UI.View.SpawnMignetteDooberCommand>(injectionBinder);
            base.commandBinder.Bind<global::Kampai.UI.View.ShowBridgeUISignal>().To<global::Kampai.UI.View.ShowBridgeBuildingUICommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.CraftingCompleteSignal>().To<global::Kampai.UI.View.CraftingCompleteCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.RemoveCraftingQueueSignal>().To<global::Kampai.UI.View.RemoveCraftingQueueCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.DisplayRandomDropIconSignal>().To<global::Kampai.UI.View.DisplayRandomDropCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.OpenStoreHighlightItemSignal>().To<global::Kampai.UI.View.OpenStoreHighlightItemCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.DragFromStoreSignal>().To<global::Kampai.UI.DragFromStoreCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.DisplayDLCDialogSignal>().To<global::Kampai.UI.View.DisplayDLCDialogCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowBuddyWelcomePanelUISignal>().To<global::Kampai.UI.View.ShowBuddyWelcomePanelUICommand>();
            base.commandBinder.Bind<global::Kampai.Game.StartPremiumPurchaseSignal>().To<global::Kampai.Game.StartPremiumPurchaseCommand>();
            base.commandBinder.Bind<global::Kampai.Game.FinishPremiumPurchaseSignal>().To<global::Kampai.Game.FinishPremiumPurchaseCommand>();
            base.commandBinder.Bind<global::Kampai.Game.CancelPremiumPurchaseSignal>().To<global::Kampai.Game.CancelPremiumPurchaseCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowMockStoreDialogSignal>().To<global::Kampai.UI.View.ShowMockStoreDialogCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowQuestPanelSignal>().To<global::Kampai.UI.View.ShowQuestPanelCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowProceduralQuestPanelSignal>().To<global::Kampai.UI.View.ShowProceduralQuestPanelCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowQuestRewardSignal>().To<global::Kampai.UI.View.ShowQuestRewardCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.CheckForLevelSignal>().To<global::Kampai.UI.CheckForLevelCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.DisplayItemPopupSignal>().To<global::Kampai.UI.View.DisplayItemPopupCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowNeedXMinionsSignal>().To<global::Kampai.UI.View.ShowNeedXMinionsCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.HideHUDAndIconsSignal>().To<global::Kampai.UI.View.HideHUDAndIconsCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowWorldCanvasSignal>().To<global::Kampai.UI.View.ShowWorldCanvasCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.DisplayLevelUpRewardSignal>().To<global::Kampai.UI.View.DisplayLevelUpRewardCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.CloseLevelUpRewardSignal>().To<global::Kampai.UI.Controller.CloseLevelUpRewardCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.OpenRateAppPageSignal>().To<global::Kampai.Common.OpenRateAppPageCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShouldRateAppSignal>().To<global::Kampai.Common.ShouldRateAppCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowRateAppPanelSignal>().To<global::Kampai.Common.ShowRateAppPanelCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowBillingNotAvailablePanelSignal>().To<global::Kampai.Common.ShowBillingNotAvailablePanelCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowTipsSignal>().To<global::Kampai.UI.View.ShowTipsCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.PopupMessageSignal>().To<global::Kampai.UI.View.PopupMessageCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.PopupMessageAtLocationSignal>().To<global::Kampai.UI.View.PopupMessageAtLocationCommand>();
            base.commandBinder.Bind<global::Kampai.Main.SetupDeepLinkSignal>().To<global::Kampai.Main.SetupDeepLinkCommand>();
            injectionBinder.Bind<global::Kampai.UI.View.HUDChangedSiblingIndexSignal>().ToSingleton().CrossContext();
            injectionBinder.Bind<global::Kampai.UI.View.PremiumCurrencyCatalogUpdatedSignal>().ToSingleton().CrossContext();
            // CONFLICT FIX: Removed duplicate binding provided by MainContext
            // injectionBinder.Bind<global::Kampai.Game.Mtx.IMtxReceiptValidationService>().To<global::Kampai.Game.Mtx.MtxReceiptValidationService>().ToSingleton().CrossContext();
            base.commandBinder.Bind<global::Kampai.Game.StartMtxReceiptValidationSignal>().To<global::Kampai.Game.Mtx.StartMtxReceiptValidationCommand>();
            base.commandBinder.Bind<global::Kampai.Game.FinishMtxReceiptValidationSignal>().To<global::Kampai.Game.Mtx.FinishMtxReceiptValidationCommand>();
            base.commandBinder.Bind<global::Kampai.Game.ProcessNextPendingTransactionSignal>().To<global::Kampai.Game.Mtx.ProcessNextPendingTransactionCommand>();
            // CONFLICT FIX: Removed duplicate binding provided by GameContext
            // injectionBinder.Bind<global::Kampai.Game.ICurrencyService>().To<global::Kampai.Game.NimbleCurrencyService>().ToSingleton().CrossContext();
            base.commandBinder.Bind<global::Kampai.Game.UserAgeForCOPPAReceivedSignal>().To<global::Kampai.Game.UserAgeForCOPPAReceivedCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyStartSignal>().To<global::Kampai.Common.ShowSocialPartyStartCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyRewardSignal>().To<global::Kampai.Common.ShowSocialPartyRewardCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyInviteSignal>().To<global::Kampai.Common.ShowSocialPartyInviteCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyInviteAlertSignal>().To<global::Kampai.Common.ShowSocialPartyInviteAlertCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyFillOrderSignal>().To<global::Kampai.Common.ShowSocialPartyFillOrderCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyFillOrderButtonSignal>().To<global::Kampai.Common.ShowSocialPartyFillOrderButtonCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyFillOrderProfileButtonSignal>().To<global::Kampai.Common.ShowSocialPartyFillOrderProfileButtonCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyFBConnectSignal>().To<global::Kampai.Common.ShowSocialPartyFBConnectCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyEventEndSignal>().To<global::Kampai.Common.ShowSocialPartyEventEndCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyEventCompletedSignal>().To<global::Kampai.Common.ShowSocialPartyEventCompletedCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowSocialPartyNoEventSignal>().To<global::Kampai.Common.ShowSocialPartyNoEventCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.ShowFacebookConnectPopupSignal>().To<global::Kampai.UI.View.ShowFacebookConnectPopupCommand>();
            base.commandBinder.Bind<global::Kampai.Game.OpenBuyBuildingModelSignal>().To<global::Kampai.Game.View.OpenBuyBuildingModelCommand>();
            base.commandBinder.Bind<global::Kampai.Game.OpenSellBuildingModalSignal>().To<global::Kampai.Game.View.OpenSellBuildingModelCommand>();
            base.commandBinder.Bind<global::Kampai.UI.View.AddFPSCounterSignal>().To<global::Kampai.UI.AddFPSCounterCommand>();
        }

        protected override void PostBindings()
        {
            if (global::strange.extensions.context.impl.Context.firstContext != this)
            {
                global::UnityEngine.AudioListener componentInChildren = (base.contextView as global::UnityEngine.GameObject).GetComponentInChildren<global::UnityEngine.AudioListener>();
                if (componentInChildren != null)
                {
                    componentInChildren.enabled = false;
                }
            }
        }
    }
}
