namespace strange.extensions.injector.api
{
	public enum InjectionExceptionType
	{
		CIRCULAR_DEPENDENCY = 0,
		ILLEGAL_BINDING_VALUE = 1,
		NO_BINDER = 2,
		NO_REFLECTOR = 3,
		NO_FACTORY = 4,
		NOT_INSTANTIABLE = 5,
		NULL_BINDING = 6,
		NULL_CONSTRUCTOR = 7,
		NULL_INJECTION_POINT = 8,
		NULL_REFLECTION = 9,
		NULL_TARGET = 10,
		NULL_VALUE_INJECTION = 11,
		SETTER_NAME_MISMATCH = 12,
		MISSING_CROSS_CONTEXT_INJECTOR = 13,
		IMPLICIT_BINDING_IMPLEMENTOR_DOES_NOT_IMPLEMENT_INTERFACE = 14,
		IMPLICIT_BINDING_TYPE_DOES_NOT_IMPLEMENT_DESIGNATED_INTERFACE = 15,
		UNINITIALIZED_ASSEMBLY = 16
	}
}
