[assembly: global::System.Reflection.AssemblyConfiguration("Release")]
[assembly: global::System.Reflection.AssemblyDefaultAlias("SharpZipLib")]
[assembly: global::System.Reflection.AssemblyProduct("#ZipLibrary")]
[assembly: global::System.Reflection.AssemblyInformationalVersion("0.86.0")]
[assembly: global::System.Reflection.AssemblyDescription("A free C# compression library")]
[assembly: global::System.Reflection.AssemblyTitle("SharpZipLib for .NET Compact Framework 2.0")]
[assembly: global::System.Reflection.AssemblyTrademark("Copyright 2001-2010 Mike Krueger, John Reilly")]
[assembly: global::System.Reflection.AssemblyCopyright("Copyright 2001-2010 Mike Krueger, John Reilly")]
[assembly: global::System.Reflection.AssemblyCompany("ICSharpCode.net")]
[assembly: global::System.Runtime.InteropServices.ComVisible(false)]
[assembly: global::System.CLSCompliant(true)]
//[assembly: global::System.Reflection.AssemblyVersion("0.86.0.518")]
