public class NimbleBridge_TrackingConstants
{
	public const string STANDARD_EVENT_PREFIX = "NIMBLESTANDARD::";

	public const string EVENT_APPSTART_NORMAL = "NIMBLESTANDARD::APPSTART_NORMAL";

	public const string EVENT_APPSTART_AFTERINSTALL = "NIMBLESTANDARD::APPSTART_AFTERINSTALL";

	public const string EVENT_APPSTART_AFTERUPGRADE = "NIMBLESTANDARD::APPSTART_AFTERUPGRADE";

	public const string EVENT_APPSTART_FROMPUSH = "NIMBLESTANDARD::APPSTART_FROMPUSH";

	public const string EVENT_APPSTART_FROMURL = "NIMBLESTANDARD::APPSTART_FROMURL";

	public const string EVENT_SESSION_START = "NIMBLESTANDARD::SESSION_START";

	public const string EVENT_APPRESUME_FROMURL = "NIMBLESTANDARD::APPRESUME_FROMURL";

	public const string EVENT_APPRESUME_NORMAL = "NIMBLESTANDARD::APPRESUME_NORMAL";

	public const string EVENT_APPRESUME_FROMPUSH = "NIMBLESTANDARD::APPRESUME_FROMPUSH";

	public const string EVENT_APPRESUME_FROMEBISU = "NIMBLESTANDARD::APPRESUME_FROMEBISU";

	public const string EVENT_SESSION_TIME = "NIMBLESTANDARD::SESSION_TIME";

	public const string EVENT_SESSION_END = "NIMBLESTANDARD::SESSION_END";

	public const string EVENT_USER_REGISTERED = "NIMBLESTANDARD::USER_REGISTERED";

	public const string EVENT_MTX_ITEM_BEGIN_PURCHASE = "NIMBLESTANDARD::MTX_ITEM_BEGIN_PURCHASE";

	public const string EVENT_MTX_ITEM_PURCHASED = "NIMBLESTANDARD::MTX_ITEM_PURCHASED";

	public const string EVENT_MTX_FREEITEM_DOWNLOADED = "NIMBLESTANDARD::MTX_FREEITEM_DOWNLOADED";

	public const string KEY_USERNAME = "NIMBLESTANDARD::KEY_MTX_USERNAME";

	public const string KEY_DURATION = "NIMBLESTANDARD::KEY_MTX_DURATION";

	public const string KEY_MTX_PRICE = "NIMBLESTANDARD::KEY_MTX_PRICE";

	public const string KEY_MTX_CURRENCY = "NIMBLESTANDARD::KEY_MTX_CURRENCY";

	public const string KEY_MTX_SELLID = "NIMBLESTANDARD::KEY_MTX_SELLID";
}
